services:
  - type: web
    name: promoz
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: cache
      mountPath: /opt/render/project/src
      sizeGB: 1
